apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlc-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      zipkin:
        endpoint: 0.0.0.0:9412
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: "reviews"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:9080"]

    exporters:
      zipkin:
        endpoint: "http://kyma-collector.kyma-system:9411/api/v2/spans"
      otlp:
        endpoint: kyma-collector.kyma-system:55680
        insecure: true
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          exporters: [otlp, logging]
        metrics:
          receivers: [prometheus]
          exporters: [otlp, logging]
