openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Kyma Connector API'
paths:
  /v1/health:
    get:
      summary: 'Returns health status'
      operationId: 'getHealth'
      tags:
        - 'health'
      responses:
        '200':
          description: 'The service is up.'
  /v1/applications/tokens:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Tenant
        schema:
          type: string
        required: true
      tags:
      - applications internal API
      summary: 'Creates a token used for certificate signing flow.'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/info/csr:
    get:
      parameters:
      - in: query
        name: token
        description: 'Access Token fetched from /tokens endpoint.'
        required: true
        schema:
          type: string
      tags:
      - applications external API
      summary: 'Allows for fetching proper information for future CSR.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrInfoResponse'
        '403':
          description: 'Invalid token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/info/urls:
    get:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - applications external API
      summary: 'Returns information on available services.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeInfoResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'              
  /v1/applications/certificates:
    post:
      parameters:
      - in: query
        name: token
        description: 'Access Token fetched from /tokens endpoint.'
        required: true
        schema:
          type: string
      tags:
      - applications external API
      summary: 'Signs CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values or lack of values in CSR.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '403':
          description: 'Invalid token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/certificates/renew:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - applications external API
      summary: 'Renews certificate using CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values or lack of values in CSR.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/certificates/revoke:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - applications external API
      summary: 'Marks certificate as revoked.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/tokens:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Tenant
        schema:
          type: string
        required: true
      tags:
      - runtimes internal API
      summary: 'Creates a token used for certificate signing flow.'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/info/csr:
      get:
        parameters:
        - in: query
          name: token
          description: 'Access Token fetched from /tokens endpoint.'
          required: true
          schema:
            type: string
        tags:
        - runtimes external API
        summary: 'Allows for fetching proper information for future CSR.'
        responses:
          '200':
            description: 'Successful operation.'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/csrInfoResponse'
          '403':
            description: 'Invalid token'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/appError'
          '500':
            description: 'Server error.'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/appError'
  /v1/runtimes/info/urls:
    get:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - runtimes external API
      summary: 'Returns information on available services.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeInfoResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/certificates:
    post:
      parameters:
      - in: query
        name: token
        description: 'Access Token fetched from /tokens endpoint.'
        required: true
        schema:
          type: string
      tags:
      - runtimes external API
      summary: 'Signs CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values or lack of values in CSR.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '403':
          description: 'Invalid token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/certificates/renew:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - runtimes external API
      summary: 'Renews certificate using CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values or lack of values in CSR.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/certificates/revoke:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - runtimes external API
      summary: 'Marks certificate as revoked.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'                         
components:
  schemas:
    tokenResponse:
      type: 'object'
      properties:
        url:
          type: 'string'
          example: 'https://cert-service.kyma.cluster.cx/v1/applications/info?token=1edfc34g'
        token:
          type: 'string'
          example: '1edfc34g'
    cert:
      type: 'object'
      properties:
        subject:
          type: 'string'
          example: 'OU=Test,O=Test,L=Blacksburg,ST=Virginia,C=US,CN={APP_NAME}'
        extensions:
          type: 'string'
        key-algorithm:
          type: 'string'
          example: 'rsa2048'
    csrApiURLs:
      type: 'object'
      properties:
        metadataUrl:
          type: 'string'
          example: 'gateway.wormhole.kyma.cluster.cx/{APP_NAME}/v1/metadata/services'
        eventsUrl:
          type: 'string'
          example: 'gateway.wormhole.kyma.cluster.cx/{APP_NAME}/v1/events'
        certificatesUrl:
          type: 'string'
          example: 'certificate-service.kyma.cluster.cx/v1/applications/{APP_NAME}'
    runtimeInfoResponse:
      type: 'object'
      properties:
        metadataUrl:
          type: 'string'
          example: 'gateway.wormhole.kyma.cluster.cx/{APP_NAME}/v1/metadata/services'
        eventsUrl:
          type: 'string'
          example: 'gateway.wormhole.kyma.cluster.cx/{APP_NAME}/v1/events'
        renewUrl:
          type: 'string'
          example: 'certificate-service.kyma.cluster.cx/v1/applications/certificates/renew'
        revokeUrl:
          type: 'string'
          example: 'certificate-service.kyma.cluster.cx/v1/applications/certificates/revoke'
        runtimeUrl:
          type: 'string'
          example: 'gateway.wormhole.kyma.cluster.cx/'
          
    csrInfoResponse:
      type: 'object'
      properties:
        url:
          type: 'string'
          example: 'https://cert-service.kyma.cluster.cx/v1/applications/{APP_NAME}/client-certs?token=1edfc34g'
        api:
          $ref: '#/components/schemas/csrApiURLs'
        certificate:
          $ref: '#/components/schemas/cert'
    appError:
      type: 'object'
      properties:
        code:
          type: 'integer'
        error:
          type: 'string'
    csrRequest:
      type: 'object'
      properties:
        csr:
          type: 'string'
          description: 'Base64 encoded certificate signing request file.'
          example: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpBTllfQ0VSVElGSUNBVEVfRklMRV9USElTX0lTX0pVU1RfQU5fRVhBTVBMRQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K'
    csrResponse:
      type: 'object'
      properties:
        crt:
          type: 'string'
          description: 'Base64 encoded certificates chain.'
          example: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCkNMSUVOVCBDRVJUSUZJQ0FURSBGSUxFIChUSElTIElTIEpVU1QgQU4gRVhBTVBMRSkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KU0VSVkVSIENFUlRJRklDQVRFIEZJTEUgKFRISVMgSVMgSlVTVCBBTiBFWEFNUExFKQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t'
