openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Kyma Connector Service API'
paths:
  /v1/health:
    get:
      summary: 'Returns health status'
      tags:
        - health API
      responses:
        '200':
          description: 'The service is up.'
  /v1/applications/tokens:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Tenant
        schema:
          type: string
        required: true
      - in: header
        name: Application
        schema:
          type: string
        required: true
      tags:
      - applications internal API
      summary: 'Creates a token used for certificate signing flow.'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        '400':
          description: 'Required headers not specified.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/certificates/revocations:
    post:
      parameters:
        - in: header
          name: Group
          schema:
            type: string
            format: uuid
          required: false
        - in: header
          name: Tenant
          schema:
            type: string
            format: uuid
          required: false
        - in: header
          name: Application
          schema:
            type: string
            format: uuid
          required: false
      tags:
        - applications internal API
      summary: 'Marks certificate as revoked.'
      responses:
        '204':
          description: 'Successful operation.'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/signingRequests/info:
    get:
      parameters:
      - in: query
        name: token
        description: 'Access Token fetched from /tokens endpoint.'
        required: true
        schema:
          type: string
      tags:
      - applications external API
      summary: 'Allows for fetching information for CSR.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrInfoResponse'
        '403':
          description: 'Invalid token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/management/info:
    get:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Tenant
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Application
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - applications external API
      summary: 'Returns information on available services.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationInfoResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/certificates:
    post:
      parameters:
      - in: query
        name: token
        description: 'Access Token fetched from /tokens endpoint.'
        required: true
        schema:
          type: string
      tags:
      - applications external API
      summary: 'Signs CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values or lack of values in CSR.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '403':
          description: 'Invalid token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/applications/certificates/renewals:
    post:
      tags:
      - applications external API
      summary: 'Renews certificate using CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values, lack of values in CSR or Group header not specified.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/tokens:
    post:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Tenant
        schema:
          type: string
        required: true
      tags:
      - runtimes internal API
      summary: 'Creates a token used for certificate signing flow.'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeTokenResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/certificates/revocations:
    post:
      parameters:
        - in: header
          name: Group
          schema:
            type: string
            format: uuid
          required: false
        - in: header
          name: Tenant
          schema:
            type: string
            format: uuid
          required: false
      tags:
        - runtimes internal API
      summary: 'Marks certificate as revoked.'
      responses:
        '204':
          description: 'Successful operation.'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/signingRequests/info:
      get:
        parameters:
        - in: query
          name: token
          description: 'Access Token fetched from /tokens endpoint.'
          required: true
          schema:
            type: string
        tags:
        - runtimes external API
        summary: 'Allows for fetching information for CSR.'
        responses:
          '200':
            description: 'Successful operation.'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/csrRuntimeInfoResponse'
          '403':
            description: 'Invalid token'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/appError'
          '500':
            description: 'Server error.'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/appError'
  /v1/runtimes/management/info:
    get:
      parameters:
      - in: header
        name: Group
        schema:
          type: string
          format: uuid
        required: true
      - in: header
        name: Tenant
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - runtimes external API
      summary: 'Returns information on available services.'
      responses:
        '200':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runtimeInfoResponse'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/certificates:
    post:
      parameters:
      - in: query
        name: token
        description: 'Access Token fetched from /tokens endpoint.'
        required: true
        schema:
          type: string
      tags:
      - runtimes external API
      summary: 'Signs CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values, lack of values in CSR or Group header not specified.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '403':
          description: 'Invalid token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
  /v1/runtimes/certificates/renewals:
    post:
      tags:
      - runtimes external API
      summary: 'Renews certificate using CSR.'
      requestBody:
        description: 'The CSR to be signed'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/csrRequest'
      responses:
        '201':
          description: 'Successful operation.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/csrResponse'
        '400':
          description: 'Improper subject values or lack of values in CSR.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
        '500':
          description: 'Server error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/appError'
components:
  schemas:
    runtimeTokenResponse:
      type: 'object'
      properties:
        url:
          type: 'string'
          example: 'https://connector-service.test.cluster.kyma.cx/v1/runtimes/info?token=1edfc34g'
        token:
          type: 'string'
          example: '1edfc34g'
    tokenResponse:
      type: 'object'
      properties:
        url:
          type: 'string'
          example: 'https://connector-service.test.cluster.kyma.cx/v1/applications/info?token=1edfc34g'
        token:
          type: 'string'
          example: '1edfc34g'
    cert:
      type: 'object'
      properties:
        subject:
          type: 'string'
          example: 'OU=Test,O=Test,L=Blacksburg,ST=Virginia,C=US,CN={TENANT}{GROUP}{APP_NAME}'
        extensions:
          type: 'string'
        key-algorithm:
          type: 'string'
          example: 'rsa2048'
    runtimeCert:
      type: 'object'
      properties:
        subject:
          type: 'string'
          example: 'OU=Test,O=Test,L=Blacksburg,ST=Virginia,C=US,CN={TENANT}{GROUP}'
        extensions:
          type: 'string'
        key-algorithm:
          type: 'string'
          example: 'rsa2048'
    csrApiURLs:
      type: 'object'
      properties:
        metadataUrl:
          type: 'string'
          example: 'gateway.test.cluster.kyma.cx/{APP_NAME}/v1/metadata/services'
        eventsUrl:
          type: 'string'
          example: 'gateway.test.cluster.kyma.cx/{APP_NAME}/v1/events'
        infoUrl:
          type: 'string'
          example: 'connector-service.test.cluster.kyma.cx/v1/applications/management/info'
    applicationInfoResponseUrls:
      type: 'object'
      properties:
        metadataUrl:
          type: 'string'
          example: 'gateway.test.cluster.kyma.cx/{APP_NAME}/v1/metadata/services'
        eventsUrl:
          type: 'string'
          example: 'gateway.test.cluster.kyma.cx/{APP_NAME}/v1/events'
        renewCertUrl:
          type: 'string'
          example: 'connector-service.test.cluster.kyma.cx/v1/applications/certificates/renewals'
        revokeCertUrl:
          type: 'string'
          example: 'connector-service.test.cluster.kyma.cx/v1/applications/certificates/revocations'
        runtimeUrl:
          type: 'string'
          example: 'test.cluster.kyma.cx/'
    applicationInfoResponse:
      type: 'object'
      properties:
        urls:
          $ref: '#/components/schemas/applicationInfoResponseUrls'
    csrInfoResponse:
      type: 'object'
      properties:
        url:
          type: 'string'
          example: 'https://connector-service.test.cluster.kyma.cx/v1/applications/certificates?token=1edfc34g'
        api:
          $ref: '#/components/schemas/csrApiURLs'
        certificate:
          $ref: '#/components/schemas/cert'
    runtimeInfoResponseUrls:
      type: 'object'
      properties:
        metadataUrl:
          type: 'string'
          example: 'gateway.test.cluster.kyma.cx/{APP_NAME}/v1/metadata/services'
        eventsUrl:
          type: 'string'
          example: 'gateway.test.cluster.kyma.cx/{APP_NAME}/v1/events'
        renewCertUrl:
          type: 'string'
          example: 'connector-service.central.cluster.kyma.cx/v1/applications/certificates/renewal'
        revokeCertUrl:
          type: 'string'
          example: 'connector-service.central.cluster.kyma.cx/v1/applications/certificates/revocations'
    runtimeInfoResponse:
      type: 'object'
      properties:
        urls:
          $ref: '#/components/schemas/runtimeInfoResponseUrls'
    csrRuntimeApiURLs:
      type: 'object'
      properties:
        infoUrl:
          type: 'string'
          example: 'connector-service.test.cluster.kyma.cx/v1/runtimes/management/info'
    csrRuntimeInfoResponse:
      type: 'object'
      properties:
        url:
          type: 'string'
          example: 'https://connector-service.test.cluster.kyma.cx/v1/runtimes/certificates?token=1edfc34g'
        api:
          $ref: '#/components/schemas/csrRuntimeApiURLs'
        certificate:
          $ref: '#/components/schemas/runtimeCert'
    appError:
      type: 'object'
      properties:
        code:
          type: 'integer'
        error:
          type: 'string'
    csrRequest:
      type: 'object'
      properties:
        csr:
          type: 'string'
          description: 'Base64 encoded certificate signing request file.'
          example: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpBTllfQ0VSVElGSUNBVEVfRklMRV9USElTX0lTX0pVU1RfQU5fRVhBTVBMRQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K'
    csrResponse:
      type: 'object'
      properties:
        crt:
          type: 'string'
          description: 'Base64 encoded certificates chain.'
          example: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCkNMSUVOVCBDRVJUSUZJQ0FURSBGSUxFIChUSElTIElTIEpVU1QgQU4gRVhBTVBMRSkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KU0VSVkVSIENFUlRJRklDQVRFIEZJTEUgKFRISVMgSVMgSlVTVCBBTiBFWEFNUExFKQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t'
