---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: docstopic.documentation.kyma-project.io
spec:
  group: documentation.kyma-project.io
  version: v1alpha1
  scope: Namespace
  names:
    plural: docstopics
    singular: docstopic
    kind: DocsTopic
    shortNames:
    - dt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            required:
              - source
            description:
              type: string
            order:
              type: integer
            displayName:
              type: string
            group:
              type: string
            contexts:
              type: array
              items:
                type: string 
            source:
              type: object
              required:
                - type
                - url
              properties:
                type:
                  type: string
                  enum:
                     - tar.gz
                     - zip
                url:
                  type: string
                content:
                  type: object
                  properties:
                    docs:
                      type: string
                    assets:
                      type: string
                    specs:
                      type: object
                      properties:
                        swagger:
                          type: object
                          required:
                              - location
                              - version
                          properties:
                            version:
                              type: string
                              enum:
                                - 2.0
                            location:
                              type: string
                        asyncapi:
                          type: object
                          required:
                              - location
                              - version
                          properties:
                            version:
                              type: string
                              enum:
                                - 1.0
                            location:
                              type: string
                        odata:
                          type: object
                          required:
                              - location
                              - version
                          properties:
                            version:
                              type: string
                              enum:
                                - 3.0
                            location:
                              type: string
---
apiVersion: documentation.kyma-project.io/v1alpha1
kind: DocsTopic
metadata:
  name: service-catalog #example based on current documentation topic https://github.com/kyma-project/kyma/tree/master/docs/service-catalog
spec:
  description: Overal documentation for Service Catalog
  order: 1 # helps with ordering of the list in navigation
  displayName: Service Catalog
  group: Components #I think that because of the plural nature of the name it is much more intuitive to expect here plural then in an attribute called "type"
  contexts: 
     - docs-view #specify in what context such documentation topic should be available, so on client side you can query to get only docs for a given context
  source:
    type: zip # and tar gz
    url: https://some.domain.com/docs.zip
    content: #specify what is in the zip and where it can be found. If not we apply our convention
      docs: ./docs
      assets: ./assets
      specs:
        - swagger:
            version: v1
            location: ./spec/swagger.json
        - asyncapi:
            version: 1.2
            location: ./spec/asyncapi.json
        - odata:
            version: 1.2
            location: ./spec/asyncapi.json
status:
  ready: False
  reason: ValidationFailed # or UploadFailed or SourceFetchFailure
  message: "swagger file is not a valid json"
#status:
#  ready: True
#  resource:
#    docsUrl: $LINK-TO-STORAGE
#    spec:
#      - type:
#          name: swagger
#          version: v1
#        url: $LINK-TO-STORAGE
