---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterdocstopic.documentation.kyma-project.io
spec:
  group: documentation.kyma-project.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: clusterdocstopics
    singular: clusterdocstopic
    kind: ClusterDocsTopic
    shortNames:
    - dt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            required:
              - source
            description:
              type: string
            order:
              type: integer
            displayName:
              type: string
            group:
              type: string
            contexts:
              type: array
              items:
                type: string 
            source:
              type: object
              properties:
                package:
                  type: object
                  required:
                    - url
                  properties
                    url:
                      type: string
                    content:
                      type: object
                      properties:
                        docs:
                          type: string
                        assets:
                          type: string
                        specs:
                          type: object
                          properties:
                            swagger:
                              type: string
                            asyncapi:
                              type: string
                            odata:
                              type: string
                docs:
                  type: string
                assets:
                  type: string
                specs:
                  type: object 
                  properties:
                    swagger:
                      type: string
                    asyncapi:
                      type: string
                    odata:
                      type: string
---
apiVersion: documentation.kyma-project.io/v1alpha1
kind: Cluster
metadata:
  name: service-catalog #example based on current documentation topic https://github.com/kyma-project/kyma/tree/master/docs/service-catalog
spec:
  description: Overal documentation for Service Catalog
  order: 1 # helps with ordering of the list in navigation
  displayName: Service Catalog
  group: Components #I think that because of the plural nature of the name it is much more intuitive to expect here plural then in an attribute called "type"
  contexts: 
     - docs-view #specify in what context such documentation topic should be available, so on client side you can query to get only docs for a given context
  source:
    package:
      url: https://some.domain.com/docs.zip
      content: #specify what is in the zip and where it can be found. Otherwise we apply convention
        docs: ./docs
        assets: ./assets
        specs:
          swagger: ./spec/swagger.json
          asyncapi: ./spec/asyncapi.json
          odata: ./spec/asyncapi.json
    docs: $LINK-TO-INDEX
    assets: $LINK-TO-INDEX
    specs:
      swagger: $LINK-TO-FILE
      asyncapi: $LINK-TO-FILE
      odata: $LINK-TO-FILE
status:
  ready: False
  reason: ValidationFailed # or UploadFailed or SourceFetchFailure
  message: "swagger file is not a valid json"
#status:
#  ready: True
#  resource:
#    docsUrl: $LINK-TO-INDEX
# .  assets: $LINK-TO-INDEX
#    spec:
#      swagger: $LINK-TO-FILE
---
#sample of index file with markdown or assets files
apiVersion: v1
files:
  - name: 01-overview.md
    metadata:
      title: MyOverview
      type: Overview
  - name: 02-details.md
    metadata:
      title: MyDetails
      type: Details
  - name: 03-installation.md
    metadata:
      title: MyInstallation
      type: Tutorial
