---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterdocstopic.documentation.kyma-project.io
spec:
  group: documentation.kyma-project.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: clusterdocstopics
    singular: clusterdocstopic
    kind: ClusterDocsTopic
    shortNames:
    - dt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            required:
              - source
            description:
              type: string
            order:
              type: integer
            displayName:
              type: string
            group:
              type: string
            source:
              type: object
              properties:
                package:
                  type: string
                      type: string
                docs:
                  type: string
                specs:
                  type: object 
                  properties:
                    swagger:
                      type: string
                    asyncapi:
                      type: string
                    odata:
                      type: string
