apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
  name: opentelemetry-collector
  namespace: kyma-system
spec:
  ports:
  - name: http-metrics
    port: 8888
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
  sessionAffinity: None
  type: ClusterIP
