apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metric-gen
  name: metric-gen
  namespace: kyma-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metric-gen
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metric-gen
    spec:
      containers:
      - image: skhalashatsap/metrics-gen:6
        imagePullPolicy: IfNotPresent
        name: metrics-gen
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
