{
 "title": "Metric Gateway",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\",  namespace=\"kyma-system\", pod=~\"telemetry-metric-gateway.*\"}, pod)"
    }
   },
   { "name": "exporter", "label": "exporter", "query": { "query": "label_values(exporter)" } }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage (WSS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"kyma-system\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"kyma-system\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"kyma-system\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kyma-system\", pod=\"$pod\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"kyma-system\", pod=\"$pod\" , resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"kyma-system\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Metrics Accepted vs Refused Received/Second",
   "type": "graph",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{pod=\"$pod\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{pod=\"$pod\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Processor Metric Received, Dropped, Accepted, Refused/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_metric_points{pod=\"$pod\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points{pod=\"$pod\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | dropped"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_metric_points{pod=\"$pod\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  },
  {
   "title": "Batches Send Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum[1m])) by (processor)",
     "legendFormat": "{{processor}} | send size sum "
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Metrics Exported vs Failed/Second",
   "type": "graph",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{exporter=~\"$exporter\", pod=\"$pod\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{exporter=~\"$exporter\", pod=\"$pod\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  {
   "title": "Exporter Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "otelcol_exporter_queue_capacity{job=\"telemetry-metric-gateway-metrics\", pod=\"$pod\"}",
     "legendFormat": "Capacity-{{ exporter }}"
    },
    {
     "expr": "otelcol_exporter_queue_size{job=\"telemetry-metric-gateway-metrics\", pod=\"$pod\"}",
     "legendFormat": "Size-{{ exporter }}"
    }
   ]
  }
 ]
}