apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: loki
spec:
  filters:
    - content: |
        Name   rewrite_tag
        Match  kube.*
        Rule   $log "^.*$" loki_rewritten true
        Emitter_Name  loki_emitter
        Emitter_Storage.type filesystem
  files:
  - content: |
      {
        "kubernetes": {
          "container_name": "container",
          "host": "node",
          "labels": {
            "app": "app",
            "app.kubernetes.io/component": "component",
            "app.kubernetes.io/name": "app",
            "serverless.kyma-project.io/function-name": "function"
          },
          "namespace_name": "namespace",
          "pod_name": "pod"
        },
        "stream": "stream"
      }
    name: labelmap.json
  outputs:
  - content: |
      Name               grafana-loki
      Alias              loki-output
      Match              loki_rewritten
      Url                http://logging-loki:3100/loki/api/v1/push
      Labels             {job="telemetry-fluent-bit"}
      RemoveKeys         kubernetes, stream
      LineFormat         json
      LogLevel           warn
      LabelMapPath       /files/labelmap.json
      storage.total_limit_size 150M
