apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  scaleConfig:
    maxReplicas: 1
    minReplicas: 1
  runtime: nodejs16
  template:
    labels:
      app: svc-a
  source:
    inline:
      source: |-
        const axios = require("axios");
        module.exports = {
            main: async function (event, context) {
              let traceId=event.extensions.request.headers['x-b3-traceid']
              console.debug(`level=debug traceId=${traceId} message=Event data: ${JSON.stringify(event.data)}`);
              
              let response = await axios.post("http://svc-b.ratelimit-test:80", event.data, {"Content-Type": "application/cloudevents+json"});
              console.info(`level=info traceId=${traceId} message=Called svc-b`);
              return response.data
          }
        };
      dependencies: |-
        {  
          "name": "svc-a",
          "version": "1.0.0",
          "dependencies":{
            "axios": "^0.21.1"
          }
        }
