apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
  namespace: kyma-system
  labels:
    app: otel-collector
data:
  config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
    processors:
      memory_limiter:
        limit_mib: 100
        spike_limit_mib: 10
        check_interval: 5s
    exporters:
      zipkin:
        # Export via zipkin for easy querying
        endpoint: http://zipkin.kyma-system.svc:9411/api/v2/spans
      logging:
        loglevel: debug
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers:
          - opencensus
          processors:
          - memory_limiter
          exporters:
          - zipkin
          - logging
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: kyma-system
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: grpc-opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: kyma-system
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: "otel/opentelemetry-collector:0.58.0"
          imagePullPolicy: IfNotPresent
          command:
            - "/otelcol"
            - "--config=/conf/config.yaml"
          ports:
            - name: grpc-opencensus
              containerPort: 55678
              protocol: TCP
          volumeMounts:
            - name: otel-collector-config
              mountPath: /conf
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 40m
              memory: 100Mi
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector
            items:
              - key: config
                path: config.yaml