# This is a sample Pod specification which contains only the entries relevant to meet the restricted Pod Security Standard from Kubernetes.
# For more details about Pod Security Standards, look here: https://kubernetes.io/docs/concepts/security/pod-security-standards.
# For more information about Pod Security Admission, and using Admission Controller to enforce Pod Security Standards, look here: https://kubernetes.io/docs/concepts/security/pod-security-admission/.
apiVersion: v1
kind: Pod
metadata:
  name: baseline-compliant-spec
  annotations:
    container.apparmor.security.beta.kubernetes.io: runtime/default # Mandatory
spec:
  securityContext:
    runAsUser: '!=0' # Optional. Use this setting only when necessary, otherwise delete it. Never set to 0 because this is the ID of root.
    runAsGroup: '!=0' # Optional. Use this setting only when necessary, otherwise delete it. Never set to 0 because this is the ID of root.
    seccompProfile: # Optional. This option can also be set on container level but it is recommended to set it on Pod level and leave it undefined on container level.
      type: RuntimeDefault
    sysctls: # Optional. Only the following calls are allowed. If it isn't necessary to modify kernel attributes (which usually should be the case), the whole sysctl-section has to be removed.
      - name: kernel.shm_rmid_forced,
        value: ''
      - name: net.ipv4.ip_local_port_range,
        value: ''
      - name: net.ipv4.ip_unprivileged_port_start,
        value: ''
      - name: net.ipv4.tcp_syncookies,
        value: ''
      - name: net.ipv4.ping_group_range,
        value: ''
  hostNetwork: false # Optional. The default is false if the entry is not there.
  hostPID: false # Optional. The default is false if the entry is not there.
  hostIPC: false # Optional. The default is false if the entry is not there.
  volumes: # hostPath volumes are not allowed. If no volumes needed, the whole volumes-section must be removed. Otherwise replace the brackets with the volumes needed.
    - []
  containers:
    - name: container-baseline
      image: ''
      command: ['']
      ports:
        - containerPort: <integer> # Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536.
          hostPort: 0 # 0 if no host port is needed. Specify a dedicated one if necessary.
      securityContext:
        privileged: false # Mandatory
        capabilities:
          add: # Only the following capabilities are allowed in the baseline standard. If no capabilities needed, the whole add-section has to be removed.
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
        seLinuxOptions: # Optional. Set this on container level and only if it is really necessary. Setting the user or role option is forbidden. If the setting is not needed, the whole seLinuxOptions-section has to be removed.
          type: container_t # or container_init_t or container_kvm_t
        procMount: default # Optional. The default is false if the entry is not there.
        readOnlyRootFilesystem: true # Mandatory
  initContainers:
    - name: init-container-baseline
      securityContext:
        privileged: false # Mandatory
        capabilities:
          add: # Only the following capabilities are allowed in the baseline standard. If no capabilities needed, the whole add-section has to be removed.
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
        seLinuxOptions: # Set this on container level and only if it is really necessary. Setting the user or role option is forbidden. If the setting is not needed, the whole seLinuxOptions-section has to be removed.
          type: container_t # or container_init_t or container_kvm_t
        procMount: default
        readOnlyRootFilesystem: true
      ports: # Delete section if it is not needed.
        - containerPort: <integer> # Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536.
          hostPort: 0 # 0 if no host port is needed. Specify a dedicated one if necessary.
