apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: mock-server
spec:
  parsers: []
  multilineParsers: []
  filters: []
  outputs:
    - content: |
        Name               http
        Alias              mock-output
        Match              kube.*
        Retry_Limit        False
        Host               mockserver.mockserver
        Port               1080
        URI                /
        Header             Content-Type application/json
        HTTP_User          user
        HTTP_Passwd        pass
        Format             json_stream
        tls                off
        tls.verify         off
        storage.total_limit_size 10M
  files: []
  secretRefs: []
