apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  name: get-started
  labels:
    cms.kyma-project.io/view-context: community
    cms.kyma-project.io/group-name: get-started
    cms.kyma-project.io/order: "1"
    cms.kyma-project.io/group-order: "1"
spec:
  displayName: "Get started"
  description: "Introduction to Kyma community"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/mmitoraj/community/archive/kyma-project-io.zip
      filter: /.kyma-project-io/get-started/
