apiVersion: rafter.kyma-project.io/v1beta1
kind: ClusterAssetGroup
metadata:
  name: release
  labels:
    rafter.kyma-project.io/view-context: community
    rafter.kyma-project.io/group-name: guidelines
    rafter.kyma-project.io/order: "4"
    rafter.kyma-project.io/group-order: "5"
spec:
  displayName: "Release"
  description: "Kyma release guidelines"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/mmitoraj/community/archive/kyma-project-io.zip
      filter: /guidelines/releases-guidelines
