apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  name: templates
  labels:
    cms.kyma-project.io/view-context: community
    cms.kyma-project.io/group-name: guidelines
    cms.kyma-project.io/order: "5"
    cms.kyma-project.io/group-order: "5"
spec:
  displayName: "Templates"
  description: "Kyma documents templates"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/mmitoraj/community/archive/kyma-project-io.zip
      filter: /guidelines/templates/
